apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: oojob
  labels:
    app: account-svc
  creationTimestamp: null
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account-svc
    spec:
      serviceAccountName: acccount-service
      containers:
        - name: account-svc
          image: docker.pkg.github.com/oojob/service-company/company:dev
          imagePullPolicy: "Never"
          resources:
            requests:
              cpu: 100m
          ports:
            - name: grpc
              containerPort: 3005
          env:
            - name: DATABASEURI
              value: "mongodb+srv://oojob:oojobN9@oojob-fxap7.mongodb.net/oojob?retryWrites=true&w=majority"
            - name: PORT
              value: 3005
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-svc
  name: account-service
  namespace: oojob
spec:
  type: LoadBalancer
  selector:
    app: account-svc
  clusterIP: None
  ports:
    - port: 3005
      targetPort: 3005
      name: grpc
