apiVersion: apps/v1
kind: Deployment
metadata:
  name: company
  namespace: oojob
spec:
  replicas: 3
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: docker.pkg.github.com/oojob/service-company/company:dev
          imagePullPolicy: "Never"
          resources:
            requests:
              cpu: 100m
          ports:
            - name: grpc
              containerPort: 3005
          env:
            - name: DATABASEURI
              value: "mongodb+srv://oojob:oojobN9@oojob-fxap7.mongodb.net/oojob?retryWrites=true&w=majority"
            - name: PORT
              value: "3005"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: company
  namespace: oojob
spec:
  selector:
    app: company
  ports:
    - name: grpc
      port: 3005
      targetPort: 3005
      protocol: TCP
  clusterIP: None
